version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install
          command: |
            apt-get update -qq && apt-get install -y --no-install-recommends make ruby emacs25-nox emacs25-el emacs24-nox elpa-flycheck
      - run:
          name: Test
          command: |
            make EMACS=emacs25
