jobs:
  test-stretch:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install
          command: |
            apt-get update -qq && apt-get install -y --no-install-recommends make ruby emacs25-nox emacs25-el emacs24-nox elpa-flycheck
      - run:
          name: Test
          command: |
            make EMACS=emacs25
  test-buster:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: Install
          command: |
            apt-get update -qq && apt-get install -y --no-install-recommends make ruby emacs-nox emacs-el elpa-flycheck
      - run:
          name: Test
          command: |
            make EMACS=emacs

workflows:
  version: 2
  test:
    jobs:
      - test-stretch
      - test-buster
